### ISSUE TITLE
Fail to initialize HT (High Throughput) PLL after embassy update

### ISSUE THREAD

**Issue by mattiasgronlund** [embassy-rs/cyw43#27]
Thanks for the good work,

I tried to update to latest git-version today, but for some reason I can not get any revision with the following commit included to work.

```
commit c385bbf07dfcadb832d02e91385bcecc45c0ef58 (HEAD)
Author: Dario Nieuwenhuis <dirbaio@dirbaio.net>
Date:   Sun Oct 2 21:28:34 2022 +0200

    Update embassy, embedded-hal.
```
For some for me still unknown reason backplane chip clock failes to enter HT mode. The startup get stuck on the following line in lib.rs.
`while self.read8(FUNC_BACKPLANE, REG_BACKPLANE_CHIP_CLOCK_CSR).await & 0x80 == 0 {}`

The commit before, c385bbf07dfcadb832d02e91385bcecc45c0ef58 works fine.

Forgot to mention that all my tests where just executed with the provided example on Raspberry PICO W

**Comment by Dirbaio** [comment]
I accidentally committed this, that's probably why: https://github.com/embassy-rs/cyw43/commit/c385bbf07dfcadb832d02e91385bcecc45c0ef58#diff-d578f52a1890582ecb4d52fa1ecfd5789ad1b75525b90b658a5d68239984d230R47

try flashing the firmware with probe-rs like that, or revert to the original lines

**Comment by Dirbaio** [comment]
I've reverted it at 27771e60afa0fe71c5512cee241400502e121b91

**Comment by mattiasgronlund** [comment]
Thanks, I tried to use the provided commands and that did it.
I think the idea of being able to pre-load the blob is really nice. But it would also be nice if it was possible to get an indication for what was wrong if one missed it.
I will for the fun of it, try to see if I can return a Result from init, which would allow the example to be more descriptive...
