### ISSUE TITLE
Why spawner.spawn needed when wifi runner.run()?

### ISSUE THREAD

**Issue by overheat** [embassy-rs/cyw43#32]
https://github.com/embassy-rs/cyw43/blob/432240162ac4131aca8aa7de61d83492f2fe3d32/examples/rpi-pico-w/src/main.rs#L71

Why I cannot change this line to `runner.run().await;`? It compiled, but not works. Log as this:
```
0.561056 INFO  waiting for wifi init...
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/aaron/embedded/cyw43/src/fmt.rs:138
0.645487 INFO  init done 
└─ cyw43::{impl#4}::init::{async_fn#0} @ /home/aaron/embedded/cyw43/src/fmt.rs:138
0.646077 WARN  BCD event, incomplete header
└─ cyw43::{impl#4}::rx @ /home/aaron/embedded/cyw43/src/fmt.rs:151
0.646131 WARN  TX stalled
└─ cyw43::{impl#4}::run::{async_fn#0} @ /home/aaron/embedded/cyw43/src/fmt.rs:151
0.646381 WARN  BCD event, incomplete header
└─ cyw43::{impl#4}::rx @ /home/aaron/embedded/cyw43/src/fmt.rs:151
```

**Comment by Dirbaio** [comment]
`runner.run()` never returns, so if you directly `.await` it the stuff after it never runs.

It needs to run in the background, concurrently with everything else. It does the low-level packet processing loop that actually sends/receives stuff over SPI, the higher layers rely on it.

**Comment by overheat** [comment]
Make sense!
Thanks
