### ISSUE TITLE
Support Bluetooth

### ISSUE THREAD

**Issue by JRedOW** [embassy-rs/cyw43#37]
Now that the official SDK supports the CYW43439's Bluetooth functionality (added in 1.5.0), will this library add support for Bluetooth?

**Comment by beeb** [comment]
Ref : https://github.com/raspberrypi/pico-sdk/issues/1164

**Comment by JRedOW** [comment]
> Ref : https://github.com/raspberrypi/pico-sdk/releases/tag/1.5.0

Thanks!

**Comment by romainreignier** [comment]
Why is this issue closed @JRedOW?
I don't see anything related to Bluetooth in this repo.

**Comment by JRedOW** [comment]
> Why is this issue closed @JRedOW? I don't see anything related to Bluetooth in this repo.

Due to the status of Bluetooth in Beta, and a lack of maintainer comment, I thought I should close this till Bluetooth is supported stably in the pico-sdk.

I will reopen it when the pico-sdk moves Bluetooth from Beta to Stable (unless Bluetooth support is added before then or any maintainers wish me to reopen it.)
