### ISSUE TITLE
Stuck on "Downloading CLM"

### ISSUE THREAD

**Issue by barafael** [embassy-rs/cyw43#44]
I am trying to run the PICO W example. I know it worked before with a previous revision of this crate, but now, I get these info prints:

```
2.857950 INFO  shared: SharedMemData { flags: 00000001, trap_addr: 00000000, assert_exp_addr: 00000000, assert_file_addr: 00000000, assert_line: 00000000, console_addr: 0006debc, msgtrace_addr: 00000000, fwid: 22213098 }
2.858024 INFO  init done 
2.858201 INFO  Downloading CLM...
```

After which nothing anymore happens.

**Comment by kbleeke** [comment]
My bad, some bug slipped back in when I tries to split my work into multiple PRs. 

The wifi task has to be spawned before issuing ioctls. Downloading the CLM data is the first ioctl that happens, so it will just be stuck there.

You can try the fix and see if it works for you.

The last few commit also switch to an new implementation using a PIO for the SPI bus. It would be interesting, if that works for anyone else but me ;). But if you get to the CTM download it should be fine.
