### ISSUE TITLE
Issue since commit

### ISSUE THREAD

**Issue by MarcoKonrad** [embassy-rs/cyw43#78]
There seems to be an issue with the current version of cyw43 that started to occure since the 0d8d8d3 commit. Since the commit, the examples do not longer work.

**Comment by kbleeke** [comment]
Seems to be a "works on my pico" issue

Do you have logs that you can share?

**Comment by MarcoKonrad** [comment]
Sure. I know that the programm loops infinite in the join_wpa2 function. The function doesnt seem to able to find the WIFI, even though its there and works perfectly fine with older version.

0.001160 INFO  Hello World!
└─ tcp_server::____embassy_main_task::{async_fn#0} @ src/bin/tcp_server.rs:47
0.272575 DEBUG waiting for clock...
└─ cyw43::runner::{impl#1}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.272699 DEBUG clock ok
└─ cyw43::runner::{impl#1}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.272969 DEBUG chip ID: 43439
└─ cyw43::runner::{impl#1}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.275796 DEBUG loading fw
└─ cyw43::runner::{impl#1}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.436784 DEBUG loading nvram
└─ cyw43::runner::{impl#1}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.437664 DEBUG starting up core...
└─ cyw43::runner::{impl#1}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.459019 DEBUG waiting for wifi init...
└─ cyw43::runner::{impl#1}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.543224 DEBUG shared_addr 00016070
└─ cyw43::runner::{impl#1}::log_init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.543528 DEBUG wifi init done
└─ cyw43::runner::{impl#1}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.543828 DEBUG Downloading CLM...
└─ cyw43::control::{impl#0}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.545943 DEBUG LOGS: 000000.001 
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.546202 DEBUG LOGS: 000000.003 sdpcmdcdc0: Broadcom SDPCMD CDC driver
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.547236 DEBUG LOGS: 000000.056 TCAM: 256 used: 76 exceed:0
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.548300 WARN  TX stalled
└─ cyw43::runner::{impl#1}::run::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:153
0.548661 WARN  BDC event, incomplete header
└─ cyw43::runner::{impl#1}::rx @ /home/mkonrad/pico/cyw43/src/fmt.rs:153
0.548784 WARN  BDC event, incomplete header
└─ cyw43::runner::{impl#1}::rx @ /home/mkonrad/pico/cyw43/src/fmt.rs:153
0.549089 WARN  IRQ DATA_UNAVAILABLE, clearing...
└─ cyw43::runner::{impl#1}::handle_irq::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:153
0.558116 DEBUG get clmload_status
└─ cyw43::control::{impl#0}::get_iovar::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.559475 DEBUG Configuring misc stuff...
└─ cyw43::control::{impl#0}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.559591 DEBUG set bus:txglom = [00, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.561020 DEBUG set apsta = [01, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.562332 DEBUG get cur_etheraddr
└─ cyw43::control::{impl#0}::get_iovar::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.563583 DEBUG mac addr: [28, cd, c1, 09, d9, 17]
└─ cyw43::control::{impl#0}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.563743 DEBUG set country = [58, 58, 00, 00, ff, ff, ff, ff, 58, 58, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.694246 DEBUG set bus:txglom = [00, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.795709 DEBUG set ampdu_ba_wsize = [08, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.897238 DEBUG set ampdu_mpdu = [04, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
0.998737 DEBUG set bsscfg:event_msgs = [00, 00, 00, 00, ff, ff, f7, ff, ff, ee, bf, ff, 7f, ff, ff, ff, ff, ff, ff, ff, ff, fd, ff, ff, ff, ff, ff, ff]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.101939 DEBUG LOGS: 000000.624 wl0: wl_open
└─ cyw43::runner::{impl#1}::log_read::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.102327 WARN  IRQ DATA_UNAVAILABLE, clearing...
└─ cyw43::runner::{impl#1}::handle_irq::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:153
1.305079 DEBUG INIT DONE
└─ cyw43::control::{impl#0}::init::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.305218 DEBUG set pm2_sleep_ret = [c8, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.306734 DEBUG set bcn_li_bcn = [01, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.308125 DEBUG set bcn_li_dtim = [01, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.309530 DEBUG set assoc_listen = [0a, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.312660 DEBUG set ampdu_ba_wsize = [08, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.313522 DEBUG DHCP send DISCOVER to 255.255.255.255: Repr { message_type: Discover, transaction_id: 3920894729, secs: 0, client_hardware_address: Address([40, 205, 193, 9, 217, 23]), client_ip: 0.0.0.0, your_ip: 0.0.0.0, server_ip: 0.0.0.0, router: None, subnet_mask: None, relay_agent_ip: 0.0.0.0, broadcast: false, requested_ip: None, client_identifier: Some(Address([40, 205, 193, 9, 217, 23])), server_identifier: None, parameter_request_list: Some([1, 3, 6]), dns_servers: None, max_size: Some(1432), lease_duration: None, renew_duration: None, rebind_duration: None, additional_options: [] }
└─ smoltcp::socket::dhcpv4::{impl#1}::dispatch @ /home/mkonrad/.cargo/registry/src/index.crates.io-6f17d22bba15001f/smoltcp-0.9.1/src/macros.rs:18
1.318671 DEBUG set bsscfg:sup_wpa = [00, 00, 00, 00, 01, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.320280 DEBUG set bsscfg:sup_wpa2_eapver = [00, 00, 00, 00, ff, ff, ff, ff]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
1.321827 DEBUG set bsscfg:sup_wpa_tmo = [00, 00, 00, 00, c4, 09, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
2.251273 DEBUG === EVENT SET_SSID: EventMessage { version: 2, flags: 0, event_type: 0, status: 3, reason: 0, auth_type: 0, datalen: 8, addr: [0, 0, 0, 0, 0, 0], ifname: [77, 6c, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ifidx: 0, bsscfgidx: 0, }  [46, 61, 63, 68, 6d, 61, 6e, 6e]
└─ cyw43::runner::{impl#1}::rx @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
2.252172 WARN  JOIN failed with status=3 auth=0
└─ cyw43::control::{impl#0}::wait_for_join::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:153
2.252276 INFO  join failed with status=3
└─ tcp_server::____embassy_main_task::{async_fn#0}::{closure#1} @ src/bin/tcp_server.rs:102
2.252368 DEBUG set ampdu_ba_wsize = [08, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
2.255219 DEBUG set bsscfg:sup_wpa = [00, 00, 00, 00, 01, 00, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
2.256719 DEBUG set bsscfg:sup_wpa2_eapver = [00, 00, 00, 00, ff, ff, ff, ff]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
2.258205 DEBUG set bsscfg:sup_wpa_tmo = [00, 00, 00, 00, c4, 09, 00, 00]
└─ cyw43::control::{impl#0}::set_iovar_v::{async_fn#0} @ /home/mkonrad/pico/cyw43/src/fmt.rs:127
3.180879 DEBUG === EVENT SET_SSID: EventMessage { version: 2, flags: 0, event_type: 0, status: 3, reason: 0, auth_type: 0, datalen: 8, addr: [0, 0, 0, 0, 0, 0], ifname: [77, 6c, 30, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], ifidx: 0, bsscfgidx: 0, }  [46, 61, 63, 68, 6d, 61, 6e, 6e]
└─ cyw43::runner::{impl#1}::rx @ /home/mkonrad/pico/cyw43/src/fmt.rs:127

After that it just infinitly loops with the same log output.

**Comment by MarcoKonrad** [comment]
I wanted to do the logs but for whatever reason it does work now. I have no clue why, maybe an crate that wasn't properly installed. 

Thanks for your help.
Keep up the good work.

Kind regards
