### ISSUE TITLE
fix README.md

### ISSUE THREAD

**Issue by papyDoctor** [embassy-rs/cyw43#82]
Hello,
When you have time and since there are three examples:
## Running the example

- `cargo install probe-rs-cli`
- `cd examples/rpi-pico-w`
Examples:
- `WIFI_NETWORK=MyWifiNetwork WIFI_PASSWORD=MyWifiPassword cargo run --release --bin tcp_server`
- `WIFI_NETWORK=MyWifiNetwork WIFI_PASSWORD=MyWifiPassword cargo run --release --bin tcp_server_ap`
- `cargo run --release --bin wifi_scan`

**Comment by Dirbaio** [comment]
Can you send a PR? Thanks!

**Comment by papyDoctor** [comment]
Ok
